# Generated by Django 5.2.11 on 2026-09-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_starred',
            field=models.BooleanField(default=False, verbose_name='Starred'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Replied At'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_content',
            field=models.TextField(blank=True, verbose_name='Last Reply Message'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_subject',
            field=models.CharField(blank=True, max_length=250, verbose_name='Last Reply Subject'),
        ),
    ]
